package client

import domain.{Movie, UserPreference}
import play.api.libs.ws._
import play.api.libs.json._
import javax.inject.{Inject, Singleton}
import scala.concurrent.{ExecutionContext, Future}

@Singleton
class MovieProviderClient @Inject()(ws: WSClient)(implicit ec: ExecutionContext) {
  
  def getMovie(title: String): Future[Option[Movie]] = {
    ws.url(s"http://localhost:9090/movie/$title").get().map { response =>
      response.json.validate[Movie] match {
        case JsSuccess(movie, _) if movie.title.nonEmpty => Some(movie)
        case _ => None
      }
    }.recover {
      case _ => None
    }
  }
  
  def addPreference(preference: UserPreference): Future[Boolean] = {
    val preferenceJson = Json.obj(
      "id" -> 0, // Will be auto-generated by database
      "userId" -> preference.userId,
      "movieId" -> preference.movieId,
      "rating" -> preference.rating
    )
    
    ws.url("http://localhost:9090/preferences")
      .post(preferenceJson)
      .map(_.status == 201)
      .recover {
        case _ => false
      }
  }
  
  def getUserPreferences(userId: String): Future[List[UserPreference]] = {
    ws.url(s"http://localhost:9090/preferences/$userId").get().map { response =>
      response.json.validate[List[JsObject]] match {
        case JsSuccess(prefs, _) => 
          prefs.flatMap { pref =>
            for {
              userId <- (pref \ "userId").asOpt[String]
              movieId <- (pref \ "movieId").asOpt[String]
              rating <- (pref \ "rating").asOpt[Int]
            } yield UserPreference(userId, movieId, rating)
          }
        case _ => List.empty
      }
    }.recover {
      case _ => List.empty
    }
  }

  def getMovieSuggestion(userId: String): Future[Option[Movie]] = {
    ws.url(s"http://localhost:9090/movie/suggestion")
      .addQueryStringParameters("userId" -> userId)
      .get().map { response =>
      response.json.validate[Movie] match {
        case JsSuccess(movie, _) if movie.title.nonEmpty => Some(movie)
        case _ => None
      }
    }.recover {
      case _ => None
    }
  }
}
